FROM registry.access.redhat.com/ubi8/ubi-minimal
ARG TARGETOS
ARG TARGETARCH
ARG BINARY
WORKDIR /
COPY ${BINARY}-${TARGETOS}-${TARGETARCH} /usr/local/bin/${BINARY}
RUN chgrp -R 0 /usr/local/bin && chmod -R 775 /usr/local/bin/${BINARY}
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/kube-rbac-proxy"]
